services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/home/ivorysql/IvorySQL:rw
    working_dir: /home/ivorysql/IvorySQL
    command: ["sleep", "infinity"]
    # Enable ptrace for gdb debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
 
  # docker compose --profile ora up -d
  oracle:
    profiles: [ora]
    image: container-registry.oracle.com/database/free:23.26.0.0-lite
    environment:
      ORACLE_PWD: orapwd
