name: regression

on:
  push:
    branches: [ master, IVORY_REL_1_STABLE ]
  pull_request:
    branches: [ master, IVORY_REL_1_STABLE ]

jobs:
  regression:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: dependancy
      if: ${{ matrix.os == 'ubuntu-18.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git lcov bison flex \
              libkrb5-dev libssl-dev libldap-dev libpam-dev python-dev \
              tcl-dev libperl-dev gettext libxml2-dev libxslt-dev \
              libreadline-dev libedit-dev uuid-dev libossp-uuid-dev \
              libipc-run-perl libtime-hires-perl libtest-simple-perl

    - name: configure - linux
      if: ${{ matrix.os == 'ubuntu-18.04' }}
      run: |
        ./configure \
            --prefix=$PWD/inst \
            --enable-cassert --enable-debug --enable-tap-tests --enable-rpath \
            --with-tcl --with-python --with-gssapi --with-pam --with-ldap \
            --with-python --with-gssapi --with-pam --with-ldap \
            --with-openssl --with-libedit-preferred --with-uuid=e2fs \
            --with-ossp-uuid  --with-libxml --with-libxslt  --with-perl

    - name: configure - macos
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        curl -L -o cpanm http://cpanmin.us && chmod +x cpanm && \
        ./cpanm --sudo IPC::Run && \
        ./configure \
            --prefix=$PWD/inst \
            --enable-cassert --enable-debug --enable-tap-tests --enable-rpath \
            --with-tcl --with-python --with-gssapi --with-pam --with-ldap \
            --with-libedit-preferred --with-uuid=e2fs --with-libxml \
            --with-libxslt --with-perl

    - name: compile
      run: make && make install

    - name: regression
      run: make check-world

    - name: collect files
      if: failure()
      run: |
          find . \( -name "*.diffs" -or -name "regression.out" -or -path \*/tmp_check/log -or -path \*src/test/regress/log \) -print0 |
                xargs -0 tar -czf regression.tar.gz

    - name: upload regression files
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: ${{ github.workspace }}/regression.tar.gz
